
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Global/Footer";
import Nav2 from "@/components/Global/Nav2";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Himtaj Jewelery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 

  return (
    
    <html lang="en">
      <body>
        <Nav2/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
